site_name: Qinghan's Personal Homepage
site_url: https://ternity.github.io/
theme:
  name: material

plugins:
  - blog:
      blog_dir: ./blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Wikis:
    - MSD学习笔记:
      - wiki/MSD/MSD_Diffusion-Coefficient_and_calculation.md
    - RDF学习笔记:
      - wiki/RDF/RDF、配位数及其在增强采样中应用.md
    - Git学习笔记:
      - wiki/Study_Git/local_hub.md
    - VASP学习笔记:
      - wiki/VASP/基于AIMD的约束MD-增强采样-自由能计算.md
  - Blog:
    - blog/index.md
    - blog/posts/hello-world.md
