site_name: Qinghan's Personal Homepage
site_url: https://ternity.github.io/
theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.sections
    - navigation.top

plugins:
  - blog:
      blog_dir: ./blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.betterem
  - pymdownx.magiclink

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - MKDocs: 
    - How_to_edit/howtodo.md
  - Wiki:
    - MSD学习笔记:
      - wiki/MSD/MSD_Diffusion-Coefficient_and_calculation.md
    - RDF学习笔记:
      - wiki/RDF/RDF、配位数及其在增强采样中应用.md
    - Git学习笔记:
      - wiki/Study_Git/local_hub.md
    - VASP学习笔记:
      - wiki/VASP/基于AIMD的约束MD-增强采样-自由能计算.md
    - 恒电势方法-电荷-极化力场系列:
      - DFT静态-AIMD-Geo-Opt下的恒电势:
        - wiki/恒电势方法-电荷-极化力场系列/DFT静态-AIMD-Geo-Opt下的恒电势/Norskov关于能垒的恒电势校正思路.md

  - Blog:
    - Start: blog/index.md
    - Hello World: blog/posts/hello-world.md
    - LaTeX with Docker: blog/posts/LaTeX_with_Docker.md
