site_name: Qinghan's Personal Homepage
site_url: https://ternity.github.io/
theme:
  name: material
  language: zh
  logo: icons/blue_notebook.png # 页面中顶部栏左侧图标
  # favicon: icons/science.png # 浏览器页面标签图标
  # icon:
    # logo: icons/science.png

  features:
    - navigation.expand     # 目录自动展开子目录
    - navigation.tabs       # 一级目录融合至顶栏，并且只展示二级目录
    - navigation.sections
    - navigation.top
    - navigation.instant.progress # 页面顶部显示加载进度条
    - content.code.copy     # 代码块复制按键
    - search.suggest        # 搜索建议
    - search.highlight      # 搜索结果高亮/突出显示
    - search.share          # 搜索结果分享

plugins:
  - blog:
      # blog_dir: ./blog
      blog_toc: true # 设置blog索引页面的目录
      post_date_format: full # 设置blog索引页面的日期格式
      archive_toc: true
      categories_toc: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last" # 设置blog索引页面的分页格式
      pagination_keep_content: true # 设置blog索引页面的分页内容
      draft_if_future_date: true # 设置如果blog的日期是未来的话，就会被当成草稿不会被发布

  # - git-revision-date-localized: # 页面下方创建和修改时间   # 由于github action新建了一个branch，文件都是最新的，所以这个时间没用
      # enable_creation_date: true
      # type: timeago
  - glightbox # 图片放大
  - search: # 搜索(选择支持中文、英文)
      separator: '[\u200b\u3000\-、。，．？！；\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang: 
        - zh
        - en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.extra
  - pymdownx.betterem
  - pymdownx.magiclink

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/extra.css

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - MKDocs: 
    - How_to_edit/howtodo.md
  - Wiki:
    - Periodic Table:
      - wiki/Periodic_Table/Periodic_Table.md
    - MSD学习笔记:
      - wiki/MSD/MSD_Diffusion-Coefficient_and_calculation.md
    - RDF学习笔记:
      - wiki/RDF/RDF、配位数及其在增强采样中应用.md
    - Git学习笔记:
      - wiki/Study_Git/local_hub.md
    - VASP学习笔记:
      - wiki/VASP/基于AIMD的约束MD-增强采样-自由能计算.md
    - 恒电势方法-电荷-极化力场系列:
      - 力场下的恒电势:
        - wiki/恒电势方法-电荷-极化力场系列/力场下的恒电势/Dipole-polarization-electric_field-force_field-constant_charge-redox_capacity.md
      - DFT静态-AIMD-Geo-Opt下的恒电势:
        - wiki/恒电势方法-电荷-极化力场系列/DFT静态-AIMD-Geo-Opt下的恒电势/Norskov关于能垒的恒电势校正思路.md
        - wiki/恒电势方法-电荷-极化力场系列/DFT静态-AIMD-Geo-Opt下的恒电势/恒电势模拟及避坑指南_DFT-基于电子的恒电势数学模型和意义.md


  - Blog:
    - blog/index.md
    # - Start: 
      # - blog/index.md
    # - Hello World: 
      # - blog/posts/hello-world.md
    # - LaTeX with Docker: 
      # - blog/posts/LaTeX_with_Docker.md

copyright: Copyright &copy; 2024 - 2024 Qinghan Yu
